# For Root
Set-PoshPrompt -Theme lambda
Import-Module Terminal-Icons
Clear-Host

Write-Host -ForegroundColor DarkRed ".     .       .  .   . .   .   . .    +  ."
Write-Host -ForegroundColor DarkRed "  .     .  :     .    .. :. .___---------___."
Write-Host -ForegroundColor DarkRed "       .  .   .    .  :.:. _ .^ .^ ^.  '.. : -_. ."
Write-Host -ForegroundColor DarkRed "    .  :       .  .  .:../:            . .^  :.:\."
Write-Host -ForegroundColor DarkRed "        .   . :: +. :.:/: .   .    .        . . .:\"
Write-Host -ForegroundColor DarkRed " .  :    .     . _ :::/:               .  ^ .  . .:\"
Write-Host -ForegroundColor DarkRed "  .. . .   . - : :.:./.                        .  .:\"
Write-Host -ForegroundColor DarkRed "  .      .     . :..|:                    .  .  ^. .:|"
Write-Host -ForegroundColor DarkRed "    .       . : : ..||        .                . . !:|"
Write-Host -ForegroundColor DarkRed "  .     . . . ::. ::\(                           . :)/"
Write-Host -ForegroundColor DarkRed " .   .     : . : .:.|. ######              .#######::|"
Write-Host -ForegroundColor DarkRed "  :.. .  :-  : .:  ::|.#######           ..########:|"
Write-Host -ForegroundColor DarkRed " .  .  .  ..  .  .. :\ ########          :######## :/"
Write-Host -ForegroundColor DarkRed "  .        .+ :: : -.:\ ########       . ########.:/"
Write-Host -ForegroundColor DarkRed "    .  .+   . . . . :.:\. #######       #######..:/"
Write-Host -ForegroundColor DarkRed "      :: . . . . ::.:..:.\           .   .   ..:/"
Write-Host -ForegroundColor DarkRed "   .   .   .  .. :  -::::.\.       | |     . .:/"
Write-Host -ForegroundColor DarkRed "      .  :  .  .  .-:. :.::.\             ..:/"
Write-Host -ForegroundColor DarkRed " .      -.   . . . .: .:::.:.\.           .:/"
Write-Host -ForegroundColor DarkRed ".   .   .  :      : ....::_:..:\   ___.  :/"
Write-Host -ForegroundColor DarkRed "   .   .  .   .:. .. .  .: :.:.:\       :/"
Write-Host -ForegroundColor DarkRed "     +   .   .   : . ::. :.:. .:.|\  .:/|"
Write-Host -ForegroundColor DarkRed "     .         +   .  .  ...:: ..|  --.:|"
Write-Host -ForegroundColor DarkRed ".      . . .   .  .  . ... :..:.. (  ..)"
Write-Host -ForegroundColor DarkRed " .   .       .      :  .   .: ::/  .  .::\"
