name: Latest blog post workflow
on:
  schedule:
    # Runs every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: neoscotch/blog-post-workflow@1.5.8
        with:
          comment_tag_name: "dispodio"
          feed_list: "https://blog.dispod.io/rss.xml"
          commit_message: "Update dispod.io blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }}         
        
