name: chat-pull-request 
on:
  pull_request:
    types: [opened, reopened]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repo
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        # https://storage.live.com/users/0x0000000000000000956d58b4cb10f2a0/myprofile/expressionprofile/profilephoto:Win8Static,UserTileMedium,UserTileStatic/MeControlXXLUserTile?ck=1&amp;ex=24
        # https://storage.live.com/users/0x0000000000000000a787b4324db7c725/myprofile/expressionprofile/profilephoto:Win8Static,UserTileMedium,UserTileStatic/MeControlXXLUserTile?ck=1&amp;ex=24
        uses: actions/checkout@v2
      
      - name: Google chatroom message
        uses: ipacheco-uy/actions-chat@v2.0.2
        with:
          # Google Chat Webhook URL
          url: ${{ secrets.CHAT_WEBHOOK }}
          project: AA
          jiraHost: https://jira.com
